//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisSayfasi
    {
        public int ID { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Sifre { get; set; }
        public int Personel_ID { get; set; }
    
        public virtual PersonelListesi PersonelListesi { get; set; }
    }
}
