//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaBilgileri()
        {
            this.AileMedikalGecmisi = new HashSet<AileMedikalGecmisi>();
            this.DonorMedikalGecmisi = new HashSet<DonorMedikalGecmisi>();
            this.EkBilgiler = new HashSet<EkBilgiler>();
            this.ImmunhistokimyaTestiDurumu = new HashSet<ImmunhistokimyaTestiDurumu>();
            this.İlaclar = new HashSet<İlaclar>();
            this.JinekolojikGecmis = new HashSet<JinekolojikGecmis>();
            this.KanserTedavisi = new HashSet<KanserTedavisi>();
            this.MetastazDurumu = new HashSet<MetastazDurumu>();
            this.Notlar = new HashSet<Notlar>();
            this.NumuneToplamaBilgileri = new HashSet<NumuneToplamaBilgileri>();
            this.OperasyonProseduru = new HashSet<OperasyonProseduru>();
            this.PatolojiDurummu = new HashSet<PatolojiDurummu>();
            this.SosyalYasamOzellikleri = new HashSet<SosyalYasamOzellikleri>();
            this.TaniBilgileri = new HashSet<TaniBilgileri>();
            this.TumorDurumu = new HashSet<TumorDurumu>();
            this.ViralEnfeksiyonlar = new HashSet<ViralEnfeksiyonlar>();
        }
    
        public int Hasta_ID { get; set; }
        public string DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Ulke { get; set; }
        public string EtnikKoken { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<int> Kilo { get; set; }
        public string EgitimSeviyesi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AileMedikalGecmisi> AileMedikalGecmisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonorMedikalGecmisi> DonorMedikalGecmisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkBilgiler> EkBilgiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImmunhistokimyaTestiDurumu> ImmunhistokimyaTestiDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<İlaclar> İlaclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JinekolojikGecmis> JinekolojikGecmis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KanserTedavisi> KanserTedavisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetastazDurumu> MetastazDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumuneToplamaBilgileri> NumuneToplamaBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperasyonProseduru> OperasyonProseduru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatolojiDurummu> PatolojiDurummu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SosyalYasamOzellikleri> SosyalYasamOzellikleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaniBilgileri> TaniBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TumorDurumu> TumorDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViralEnfeksiyonlar> ViralEnfeksiyonlar { get; set; }
    }
}
