//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImmunhistokimyaTestiDurumu
    {
        public int TestDurumu_ID { get; set; }
        public string ERTestDurumu { get; set; }
        public string ERSonuc { get; set; }
        public string PRTestDurumu { get; set; }
        public string PRSonuc { get; set; }
        public string HER2TestDurumu { get; set; }
        public string HER2Sonuc { get; set; }
        public string MLH1TestDurumu { get; set; }
        public string MLH1Sonuc { get; set; }
        public string PMS2TestDurumu { get; set; }
        public string PMS2Sonuc { get; set; }
        public string MSH2TestDurumu { get; set; }
        public string MSH2Sonuc { get; set; }
        public string MSH6TestDurumu { get; set; }
        public string MSH6Sonuc { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
    
        public virtual HastaBilgileri HastaBilgileri { get; set; }
    }
}
