//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlaclar
    {
        public int İlac_ID { get; set; }
        public string İlac { get; set; }
        public Nullable<byte> Doz { get; set; }
        public string Birim { get; set; }
        public string KullanimSekli { get; set; }
        public string Siklik { get; set; }
        public string MevcutDurum { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
    
        public virtual HastaBilgileri HastaBilgileri { get; set; }
    }
}
