//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetastazDurumu
    {
        public int Metastaz_ID { get; set; }
        public string MetastazOrgani { get; set; }
        public string LenfNoduIslemi { get; set; }
        public string LenfNoduMetastazi { get; set; }
        public string LenfNoduLokasyon { get; set; }
        public string UzakMetastaz { get; set; }
        public string UzakMetastazLokasyon { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
    
        public virtual HastaBilgileri HastaBilgileri { get; set; }
    }
}
