//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeIT_DBContext : DbContext
    {
        public ProjeIT_DBContext()
            : base("name=ProjeIT_DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AileMedikalGecmisi> AileMedikalGecmisi { get; set; }
        public virtual DbSet<DonorMedikalGecmisi> DonorMedikalGecmisi { get; set; }
        public virtual DbSet<EkBilgiler> EkBilgiler { get; set; }
        public virtual DbSet<GirisSayfasi> GirisSayfasi { get; set; }
        public virtual DbSet<HastaBilgileri> HastaBilgileri { get; set; }
        public virtual DbSet<ImmunhistokimyaTestiDurumu> ImmunhistokimyaTestiDurumu { get; set; }
        public virtual DbSet<İlaclar> İlaclar { get; set; }
        public virtual DbSet<JinekolojikGecmis> JinekolojikGecmis { get; set; }
        public virtual DbSet<KanserTedavisi> KanserTedavisi { get; set; }
        public virtual DbSet<MetastazDurumu> MetastazDurumu { get; set; }
        public virtual DbSet<Notlar> Notlar { get; set; }
        public virtual DbSet<NumuneToplamaBilgileri> NumuneToplamaBilgileri { get; set; }
        public virtual DbSet<OperasyonProseduru> OperasyonProseduru { get; set; }
        public virtual DbSet<PatolojiDurummu> PatolojiDurummu { get; set; }
        public virtual DbSet<PersonelListesi> PersonelListesi { get; set; }
        public virtual DbSet<SosyalYasamOzellikleri> SosyalYasamOzellikleri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaniBilgileri> TaniBilgileri { get; set; }
        public virtual DbSet<TumorDurumu> TumorDurumu { get; set; }
        public virtual DbSet<ViralEnfeksiyonlar> ViralEnfeksiyonlar { get; set; }
        public virtual DbSet<TumTablolar> TumTablolar { get; set; }
    }
}
