//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumuneToplamaBilgileri
    {
        public int Numune_ID { get; set; }
        public string ToplamaTarihi { get; set; }
        public string ToplamaSaati { get; set; }
        public string AnatomikBolge { get; set; }
        public string ToplamaSekli { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
    
        public virtual HastaBilgileri HastaBilgileri { get; set; }
    }
}
