//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SosyalYasamOzellikleri
    {
        public int SosyalYasamID { get; set; }
        public string Meslek { get; set; }
        public string CevreselMaruziyet { get; set; }
        public Nullable<bool> SigaraDurum { get; set; }
        public string SigaraTip { get; set; }
        public Nullable<int> SigaraMiktar { get; set; }
        public Nullable<int> SigaraMevcutDurum { get; set; }
        public string SigaraBirakis { get; set; }
        public Nullable<bool> AlkolDurum { get; set; }
        public string AlkolTip { get; set; }
        public Nullable<int> AlkolMiktar { get; set; }
        public Nullable<int> AlkolMevcutDurum { get; set; }
        public string AlkolBirakis { get; set; }
        public Nullable<bool> MaddeDurum { get; set; }
        public string MaddeTip { get; set; }
        public Nullable<int> MaddeMiktar { get; set; }
        public Nullable<int> MaddeMevcutDurum { get; set; }
        public string MaddeBirakis { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
    
        public virtual HastaBilgileri HastaBilgileri { get; set; }
    }
}
