//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumTablolar
    {
        public int Hasta_ID { get; set; }
        public string DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Ulke { get; set; }
        public string EtnikKoken { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<int> Kilo { get; set; }
        public string EgitimSeviyesi { get; set; }
        public string Meslek1 { get; set; }
        public string CevreselMaruziyet { get; set; }
        public Nullable<bool> SigaraDurum { get; set; }
        public string SigaraTip { get; set; }
        public Nullable<int> SigaraMiktar { get; set; }
        public Nullable<int> SigaraMevcutDurum { get; set; }
        public string SigaraBirakis { get; set; }
        public Nullable<bool> AlkolDurum { get; set; }
        public string AlkolTip { get; set; }
        public Nullable<int> AlkolMiktar { get; set; }
        public Nullable<int> AlkolMevcutDurum { get; set; }
        public string AlkolBirakis { get; set; }
        public Nullable<bool> MaddeDurum { get; set; }
        public string MaddeTip { get; set; }
        public Nullable<int> MaddeMiktar { get; set; }
        public Nullable<int> MaddeMevcutDurum { get; set; }
        public string MaddeBirakis { get; set; }
        public string HastalikTedavi { get; set; }
        public string TaniTarihi { get; set; }
        public string Durumu { get; set; }
        public string ICD10Kodu { get; set; }
        public string Yakinlik { get; set; }
        public string Tani { get; set; }
        public Nullable<int> TaniYili { get; set; }
        public string MenstrualDurum { get; set; }
        public string SonReglTarihi { get; set; }
        public string Hamilelik { get; set; }
        public string Dogum { get; set; }
        public string İlac { get; set; }
        public Nullable<byte> Doz { get; set; }
        public string Birim { get; set; }
        public string KullanimSekli { get; set; }
        public string Siklik { get; set; }
        public string MevcutDurum { get; set; }
        public string HIVTestDurumu { get; set; }
        public string HIVSonuc { get; set; }
        public string HepATestDurumu { get; set; }
        public string HepASonuc { get; set; }
        public string HepBTestDurumu { get; set; }
        public string HepBSonuc { get; set; }
        public string HepCTestDurumu { get; set; }
        public string HepCSonuc { get; set; }
        public string SifilizTestDurumu { get; set; }
        public string SifilizSonuc { get; set; }
        public string ToplamaTarihi { get; set; }
        public string ToplamaSaati { get; set; }
        public string AnatomikBolge { get; set; }
        public string ToplamaSekli { get; set; }
        public string OperasyonProseduru { get; set; }
        public string TaniTarihi1 { get; set; }
        public string KlinikTani { get; set; }
        public string ICD10TaniKodu { get; set; }
        public string NumuneToplamaSekli { get; set; }
        public string MikroskopikAnaliz { get; set; }
        public string PatolojikTani { get; set; }
        public string TumorBolgesi { get; set; }
        public string TumorBoyutu { get; set; }
        public string TNM { get; set; }
        public string Evre { get; set; }
        public string TumorTipi { get; set; }
        public string MetastazOrgani { get; set; }
        public string LenfNoduIslemi { get; set; }
        public string LenfNoduMetastazi { get; set; }
        public string LenfNoduLokasyon { get; set; }
        public string UzakMetastaz { get; set; }
        public string UzakMetastazLokasyon { get; set; }
        public string TedaviTipi { get; set; }
        public string TedaviBaslangicBitis { get; set; }
        public string TedaviSonucu { get; set; }
        public string TedaviUygulamaSekli { get; set; }
        public string ERTestDurumu { get; set; }
        public string ERSonuc { get; set; }
        public string PRTestDurumu { get; set; }
        public string PRSonuc { get; set; }
        public string HER2TestDurumu { get; set; }
        public string HER2Sonuc { get; set; }
        public string MLH1TestDurumu { get; set; }
        public string MLH1Sonuc { get; set; }
        public string PMS2TestDurumu { get; set; }
        public string PMS2Sonuc { get; set; }
        public string MSH2TestDurumu { get; set; }
        public string MSH2Sonuc { get; set; }
        public string MSH6TestDurumu { get; set; }
        public string MSH6Sonuc { get; set; }
        public string EkIslemler { get; set; }
        public string Notlar { get; set; }
        public Nullable<int> Personel_ID { get; set; }
    }
}
