//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCRF_ProjeIT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViralEnfeksiyonlar
    {
        public int Viral_ID { get; set; }
        public string HIVTestDurumu { get; set; }
        public string HIVSonuc { get; set; }
        public string HepATestDurumu { get; set; }
        public string HepASonuc { get; set; }
        public string HepBTestDurumu { get; set; }
        public string HepBSonuc { get; set; }
        public string HepCTestDurumu { get; set; }
        public string HepCSonuc { get; set; }
        public string SifilizTestDurumu { get; set; }
        public string SifilizSonuc { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
    
        public virtual HastaBilgileri HastaBilgileri { get; set; }
    }
}
